### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by chenjunhao0315** [randomplum/homebrew-gtkwave#1]
When I try to install via homebrew, the failure occurs when applying macos_compact.diff.

==> Applying macos_compat.diff
patching file meson.build
patching file 'src/cocoa/cocoa_misc.c'
patching file 'src/cocoa/cocoa_misc.h'
patching file 'src/globals.h'
1 out of 1 hunks failed--saving rejects to 'src/globals.h.rej'
patching file 'src/main.c'
patching file 'src/meson.build'
patching file 'src/wave_view.c'

Can you help me to fix it?

**Comment by randomplum** [comment]
One of the changes already got merged in upstream. Until gtkwave gets 3.4.0 release this will happen occasionally. I'm working on including all required changes in upstream so we don't need any patches and are ready for inclusion in homebrew official repos.

I'm updated the formula and the patch. should work. Thanks for reporting.
